# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "cvlad"
description:        "a clean, lightweight and minimalistic blog theme for jekyll"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//cvlad.info"
author:             "cvlad"
twitter:
  username:         "cvlad"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
#  - name:           "About"
#    href:           "/about"
  - name:           "Github"
    href:           "//github.com/vladciobanu/"
  - name:           "Twitter"
    href:           "//twitter.com/cvlad"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
